// Minimal Tauri 2 app for Spike 2 — proves the asset:// protocol streams a
// ~100MB file into the renderer without OOM and within the <2s target.
//
// One command: `fixture_path` returns the absolute path of the spike fixture
// (generated by `node gen-fixture.mjs` before launch). The frontend converts
// it via `@tauri-apps/api/core:convertFileSrc` and fetches the URL.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::path::PathBuf;

#[tauri::command]
fn fixture_path() -> Result<String, String> {
    // `CARGO_MANIFEST_DIR` is baked in at compile time. The binary still
    // needs the fixture at the same absolute path at runtime — we only ever
    // run this via `cargo run` from the spike directory, so that's fine.
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let file = dir.join("fixture-100mb.stl");
    if !file.exists() {
        return Err(format!(
            "fixture not found at {}. Run `node gen-fixture.mjs` first.",
            file.display()
        ));
    }
    Ok(file.to_string_lossy().into_owned())
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![fixture_path])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
